### ISSUE TITLE
Format RA_d and DEC_d

### ISSUE THREAD

**Issue by marixko** [splus-collab/check_infoot#1]
The format of RA_d and DEC_d columns seems broken, can you check this please?

![image](https://github.com/splus-collab/check_infoot/assets/14929100/142468f3-10cf-4b73-ad44-8b6d15ec5395)

**Comment by herpichfr** [comment]
Thanks for pointing this out. Those columns shouldn't even be there, given that the code calculates the coordinates in deg from the RA and DEC columns already present in the data.
